services:
  fm_keystone.user_manager:
    class: FM\KeystoneBundle\Manager\UserManager
    arguments: [@security.encoder_factory, @doctrine.orm.entity_manager, %fm_keystone.model.user.class%]

  fm_keystone.user_manipulator:
    class: FM\KeystoneBundle\Util\UserManipulator
    arguments: [@fm_keystone.user_manager]

  fm_keystone.token_manager:
    class: FM\KeystoneBundle\Manager\TokenManager
    arguments: [@fm_keystone.security.encoder.token, @doctrine.orm.entity_manager]

  fm_keystone.service_manager:
    class: FM\KeystoneBundle\Manager\ServiceManager
    arguments: [@doctrine.orm.entity_manager]

  fm_keystone.kernel.listener.exception:
    class: FM\KeystoneBundle\EventListener\ExceptionListener
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 1000 }
